// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ZboruriDbContext))]
    partial class ZboruriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Model.Angajat", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("angajati", (string)null);
                });

            modelBuilder.Entity("Model.Bilet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NrLocuri")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZborId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZborId");

                    b.ToTable("bilete", (string)null);
                });

            modelBuilder.Entity("Model.TuristBilet", b =>
                {
                    b.Property<int>("BiletId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turist")
                        .HasColumnType("TEXT");

                    b.HasKey("BiletId", "Turist");

                    b.ToTable("turisti_bilet", (string)null);
                });

            modelBuilder.Entity("Model.Zbor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aeroport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destinatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NrLocuri")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plecare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("zboruri", (string)null);
                });

            modelBuilder.Entity("Model.Bilet", b =>
                {
                    b.HasOne("Model.Zbor", "Zbor")
                        .WithMany()
                        .HasForeignKey("ZborId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zbor");
                });

            modelBuilder.Entity("Model.TuristBilet", b =>
                {
                    b.HasOne("Model.Bilet", "Bilet")
                        .WithMany("Turisti")
                        .HasForeignKey("BiletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bilet");
                });

            modelBuilder.Entity("Model.Bilet", b =>
                {
                    b.Navigation("Turisti");
                });
#pragma warning restore 612, 618
        }
    }
}
